// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/policy.proto

package policy

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyRequest) Reset() {
	*x = PolicyRequest{}
	mi := &file_proto_policy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyRequest) ProtoMessage() {}

func (x *PolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_policy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyRequest.ProtoReflect.Descriptor instead.
func (*PolicyRequest) Descriptor() ([]byte, []int) {
	return file_proto_policy_proto_rawDescGZIP(), []int{0}
}

func (x *PolicyRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type PolicyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Capacity      float64                `protobuf:"fixed64,2,opt,name=capacity,proto3" json:"capacity,omitempty"`
	RefillRate    float64                `protobuf:"fixed64,3,opt,name=refill_rate,json=refillRate,proto3" json:"refill_rate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyResponse) Reset() {
	*x = PolicyResponse{}
	mi := &file_proto_policy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyResponse) ProtoMessage() {}

func (x *PolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_policy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyResponse.ProtoReflect.Descriptor instead.
func (*PolicyResponse) Descriptor() ([]byte, []int) {
	return file_proto_policy_proto_rawDescGZIP(), []int{1}
}

func (x *PolicyResponse) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PolicyResponse) GetCapacity() float64 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *PolicyResponse) GetRefillRate() float64 {
	if x != nil {
		return x.RefillRate
	}
	return 0
}

var File_proto_policy_proto protoreflect.FileDescriptor

const file_proto_policy_proto_rawDesc = "" +
	"\n" +
	"\x12proto/policy.proto\x12\x06policy\"!\n" +
	"\rPolicyRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"_\n" +
	"\x0ePolicyResponse\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1a\n" +
	"\bcapacity\x18\x02 \x01(\x01R\bcapacity\x12\x1f\n" +
	"\vrefill_rate\x18\x03 \x01(\x01R\n" +
	"refillRate2K\n" +
	"\rPolicyService\x12:\n" +
	"\tGetPolicy\x12\x15.policy.PolicyRequest\x1a\x16.policy.PolicyResponseB'Z%distributed-rate-limiter/proto;policyb\x06proto3"

var (
	file_proto_policy_proto_rawDescOnce sync.Once
	file_proto_policy_proto_rawDescData []byte
)

func file_proto_policy_proto_rawDescGZIP() []byte {
	file_proto_policy_proto_rawDescOnce.Do(func() {
		file_proto_policy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_policy_proto_rawDesc), len(file_proto_policy_proto_rawDesc)))
	})
	return file_proto_policy_proto_rawDescData
}

var file_proto_policy_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_policy_proto_goTypes = []any{
	(*PolicyRequest)(nil),  // 0: policy.PolicyRequest
	(*PolicyResponse)(nil), // 1: policy.PolicyResponse
}
var file_proto_policy_proto_depIdxs = []int32{
	0, // 0: policy.PolicyService.GetPolicy:input_type -> policy.PolicyRequest
	1, // 1: policy.PolicyService.GetPolicy:output_type -> policy.PolicyResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_policy_proto_init() }
func file_proto_policy_proto_init() {
	if File_proto_policy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_policy_proto_rawDesc), len(file_proto_policy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_policy_proto_goTypes,
		DependencyIndexes: file_proto_policy_proto_depIdxs,
		MessageInfos:      file_proto_policy_proto_msgTypes,
	}.Build()
	File_proto_policy_proto = out.File
	file_proto_policy_proto_goTypes = nil
	file_proto_policy_proto_depIdxs = nil
}
